export enum EIconTypes {
  email = 'email',
  password = 'password',
  rightChevron = 'rightChevron',
  leftChevron = 'leftChevron',
  search = 'search',
  infoCircle = 'infoCircle',
  closeCircle = 'closeCircle',
  check = 'check',
  paperPlane = 'paperPlane',
  account = 'account',
  downChevron = 'downChevron',
  signOut = 'signOut',
  smile = 'smile',
  usersCog = 'usersCog',
  userPlus = 'userPlus',
  group = 'group',
  plus = 'plus',
  userEdit = 'userEdit',
  cross = 'cross',
  pencil = 'pencil',
  trash = 'trash',
  questionMark = 'questionMark',
  userSettings = 'userSettings',
}
